### ISSUE TITLE
Unicode normalisation

### ISSUE THREAD

**Issue by ngawangtrinley** [Esukhia/botok#45]
Add a Unicode normalization method for bad/ambiguous unicode:
https://github.com/Esukhia/derge-tengyur/blob/c45da1faabef28ff0b037557499bf07946e5c3ab/scripts/error-report.py#L44

**Comment by eroux** [comment]
Unfortunately It's not automatable, every case is different.

To take an example sometimes there are two drengbu instead of a double drengbu, sometimes instead of one drengbu... same for unattached diacritics, sometimes they should be attached to what's after, sometimes to what's before. I think I've fixed everything that could be fixed fully automatically, except punctuation maybe... unless you had something specific in mind?

**Comment by drupchen** [comment]
as a start: https://github.com/Esukhia/adarsha2esukhia/blob/master/adarsha2esukhia.py#L90

**Comment by eroux** [comment]
other idea: 0F6A to 0F62 when no subscribed or the subscribed that don't change the shape of the rago (like nya)

**Comment by drupchen** [comment]
closed here because this issue pertains to pybo
