### ISSUE TITLE
Huge memory cost when initializing the tokenizer

### ISSUE THREAD

**Issue by BLKSerene** [Esukhia/botok#56]
Hi, the memory cost is extremely high on my 64-bit Windows 10 when initializing the tokenizer, ~1600MB for the GMD profile, ~600MB for the POS profile, ~500MB for the tsikchen profile, no matter building the trie from scratch or loading the existing trie file.

And the memory in use does not decrease after the tokenizer is initialized, is this the expected behavior?

**Comment by drupchen** [comment]
I did not expect it to consume so much memory. The pickled trie weights about 19Mo for POS profile, so I never thought it would require 600+Mo in memory.
I'll check if there is anything else than the loaded trie that takes so much memory.

**Comment by drupchen** [comment]
I have just tested to build the tries on a syllable basis instead of a char basis, meaning there will be one node per syllable instead of about 4 or 5 of them.
It does significantly reduce de trie size. I can't compare the performance of the tokenizer since it is not meant for such a trie.

It does look like a good improvement, memory usage wise

```bash
Loading Trie... (3s.)
Loading Trie... (2s.)
Loading Trie... (1s.)

Line #    Increment   Line Contents
================================================
    11    691.4 MiB      gmd = get_tok('GMD')
    12    116.7 MiB      pos = get_tok('POS')
    13    186.9 MiB      tsik = get_tok('tsikchen')


```

**Comment by 10zinten** [comment]
We have improved tokenizer to work on syllable based Trie (as @drupchen has described above)
